name: Test Python with Cache
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
          cache: 'poetry'
      - run: poetry install

      - name: Verify cache path
        run: |
          if [ -d ~/.cache/pypoetry ]; then
            echo "Cache directory exists."
          else
            echo "Cache directory does not exist."
          fi

      - name: List cache directory
        run: ls -la ~/.cache/pypoetry